version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - '80:80'
    depends_on:
      - api
  backend:
    build: ./backend
    ports:
      - '8080:8080'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'

