version: '3.8'
services:
  frontend:
    build: ./frontend
    image: heikkitanhi/harjoitus_frontend
    ports:
      - '80:80'
    depends_on:
      - backend
  backend:
    build: ./backend
    image: heikkitanhi/harjoitus_backend
    ports:
      - '8080:8080'
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_NAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    ports:
      - '27017:27017'

